package com.mochasoft.fk.security.mapper;

import com.mochasoft.fk.mapper.MyBatisRepository;
import com.mochasoft.fk.security.entity.Permission;
import java.util.List;

@MyBatisRepository
public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_PERMISSION
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_PERMISSION
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_PERMISSION
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    Permission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_PERMISSION
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    List<Permission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_PERMISSION
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int updateByPrimaryKey(Permission record);
}