package com.mochasoft.fk.security.mapper;

import com.mochasoft.fk.mapper.MyBatisRepository;
import com.mochasoft.fk.security.entity.PermissionResource;
import java.util.List;

@MyBatisRepository
public interface PermissionResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_PERMISSION_RES
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_PERMISSION_RES
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int insert(PermissionResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_PERMISSION_RES
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    PermissionResource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_PERMISSION_RES
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    List<PermissionResource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_PERMISSION_RES
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int updateByPrimaryKey(PermissionResource record);
}