package com.mochasoft.fk.security.mapper;

import com.mochasoft.fk.mapper.MyBatisRepository;
import com.mochasoft.fk.security.entity.RoleUser;
import java.util.List;

@MyBatisRepository
public interface RoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_ROLE_USER
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_ROLE_USER
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int insert(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_ROLE_USER
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    RoleUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_ROLE_USER
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    List<RoleUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_ROLE_USER
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int updateByPrimaryKey(RoleUser record);
	
    /**
     * 根据用户userId获取用户的所有角色名称.
     * @param userId
     * @return 角色名称列表
     */
    List<String> selectByUserId(String userId);
}