package com.mochasoft.fk.security.mapper;

import com.mochasoft.fk.mapper.MyBatisRepository;
import com.mochasoft.fk.security.entity.Role;
import com.mochasoft.fk.security.entity.RoleResource;

import java.util.List;

@MyBatisRepository
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_ROLE
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_ROLE
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_ROLE
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    Role selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_ROLE
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_ROLE
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int updateByPrimaryKey(Role record);
    
    /**
     * 获取Role和Resource的对应关系.
     * @return Role和Resource的对应关系
     */
    List<RoleResource> selectAllRoleResource();
}