package com.mochasoft.fk.security.mapper;

import com.mochasoft.fk.mapper.MyBatisRepository;
import com.mochasoft.fk.security.entity.User;
import java.util.List;

@MyBatisRepository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_USER
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_USER
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_USER
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_USER
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOCHA_SECU_USER
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    int updateByPrimaryKey(User record);
    
    /**
     * 根据userid查询Users对象.
     * @param username
     * @return
     */
    User selectByUserid(String userid);

	/**
	 * 根据userid修改密码:使用userid和password做为参数，修改password字段.
	 * @param users
	 */
	void changePassword(User users);
}