package com.mochasoft.example.mapper;

import java.util.List;

import com.mochasoft.example.entity.UserInfo;
import com.mochasoft.fk.mapper.MyBatisRepository;

@MyBatisRepository
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    int deleteByPrimaryKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    UserInfo selectByPrimaryKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    int updateByPrimaryKey(UserInfo record);
}