package com.mochasoft.example.entity;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.id
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.username
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.password
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.email
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_userinfo.mobile
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    private String mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.id
     *
     * @return the value of t_userinfo.id
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.id
     *
     * @param id the value for t_userinfo.id
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.username
     *
     * @return the value of t_userinfo.username
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.username
     *
     * @param username the value for t_userinfo.username
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.password
     *
     * @return the value of t_userinfo.password
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.password
     *
     * @param password the value for t_userinfo.password
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.email
     *
     * @return the value of t_userinfo.email
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.email
     *
     * @param email the value for t_userinfo.email
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_userinfo.mobile
     *
     * @return the value of t_userinfo.mobile
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_userinfo.mobile
     *
     * @param mobile the value for t_userinfo.mobile
     *
     * @mbggenerated Fri Jan 11 11:38:31 CST 2013
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("id:")
				.append(this.id)
				.append(",username:")
				.append(this.username)
				.append(",password:")
				.append(this.password)
				.append(",email:")
				.append(this.email)
				.append(",mobile:")
				.append(this.mobile)
				.append("\n");
		return builder.toString();
	}
    
    
}