package com.mochasoft.fk.configuration.entity;

public class Configuration {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_CONFIGURATION.ID
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_CONFIGURATION.TYPE
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_CONFIGURATION.KEY
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_CONFIGURATION.VALUE
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_CONFIGURATION.LASTUPDATETIME
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    private Long lastupdatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_CONFIGURATION.ID
     *
     * @return the value of MOCHA_SECU_CONFIGURATION.ID
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_CONFIGURATION.ID
     *
     * @param id the value for MOCHA_SECU_CONFIGURATION.ID
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_CONFIGURATION.TYPE
     *
     * @return the value of MOCHA_SECU_CONFIGURATION.TYPE
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_CONFIGURATION.TYPE
     *
     * @param type the value for MOCHA_SECU_CONFIGURATION.TYPE
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_CONFIGURATION.KEY
     *
     * @return the value of MOCHA_SECU_CONFIGURATION.KEY
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_CONFIGURATION.KEY
     *
     * @param key the value for MOCHA_SECU_CONFIGURATION.KEY
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_CONFIGURATION.VALUE
     *
     * @return the value of MOCHA_SECU_CONFIGURATION.VALUE
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_CONFIGURATION.VALUE
     *
     * @param value the value for MOCHA_SECU_CONFIGURATION.VALUE
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_CONFIGURATION.LASTUPDATETIME
     *
     * @return the value of MOCHA_SECU_CONFIGURATION.LASTUPDATETIME
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    public Long getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_CONFIGURATION.LASTUPDATETIME
     *
     * @param lastupdatetime the value for MOCHA_SECU_CONFIGURATION.LASTUPDATETIME
     *
     * @mbggenerated Tue Jan 29 17:16:49 CST 2013
     */
    public void setLastupdatetime(Long lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }
}