package com.mochasoft.fk.security.entity;

public class PermissionResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_PERMISSION_RES.ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_PERMISSION_RES.PER_ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String PerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_PERMISSION_RES.RES_ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String resId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_PERMISSION_RES.ID
     *
     * @return the value of MOCHA_SECU_PERMISSION_RES.ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_PERMISSION_RES.ID
     *
     * @param id the value for MOCHA_SECU_PERMISSION_RES.ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_PERMISSION_RES.PER_ID
     *
     * @return the value of MOCHA_SECU_PERMISSION_RES.PER_ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getPerId() {
        return PerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_PERMISSION_RES.PER_ID
     *
     * @param PerId the value for MOCHA_SECU_PERMISSION_RES.PER_ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setPerId(String PerId) {
        this.PerId = PerId == null ? null : PerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_PERMISSION_RES.RES_ID
     *
     * @return the value of MOCHA_SECU_PERMISSION_RES.RES_ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_PERMISSION_RES.RES_ID
     *
     * @param resId the value for MOCHA_SECU_PERMISSION_RES.RES_ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setResId(String resId) {
        this.resId = resId == null ? null : resId.trim();
    }
}