package com.mochasoft.fk.security.entity;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_RESOURCE.ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_RESOURCE.NAME
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_RESOURCE.RES_TYPE
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String resType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_RESOURCE.RESOURCES
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String resources;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_RESOURCE.ORDER_NUM
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_RESOURCE.CREATE_TIME
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_RESOURCE.DESCN
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String descn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_RESOURCE.ID
     *
     * @return the value of MOCHA_SECU_RESOURCE.ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_RESOURCE.ID
     *
     * @param id the value for MOCHA_SECU_RESOURCE.ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_RESOURCE.NAME
     *
     * @return the value of MOCHA_SECU_RESOURCE.NAME
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_RESOURCE.NAME
     *
     * @param name the value for MOCHA_SECU_RESOURCE.NAME
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_RESOURCE.RES_TYPE
     *
     * @return the value of MOCHA_SECU_RESOURCE.RES_TYPE
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getResType() {
        return resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_RESOURCE.RES_TYPE
     *
     * @param resType the value for MOCHA_SECU_RESOURCE.RES_TYPE
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setResType(String resType) {
        this.resType = resType == null ? null : resType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_RESOURCE.RESOURCES
     *
     * @return the value of MOCHA_SECU_RESOURCE.RESOURCES
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getResources() {
        return resources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_RESOURCE.RESOURCES
     *
     * @param resources the value for MOCHA_SECU_RESOURCE.RESOURCES
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setResources(String resources) {
        this.resources = resources == null ? null : resources.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_RESOURCE.ORDER_NUM
     *
     * @return the value of MOCHA_SECU_RESOURCE.ORDER_NUM
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_RESOURCE.ORDER_NUM
     *
     * @param orderNum the value for MOCHA_SECU_RESOURCE.ORDER_NUM
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_RESOURCE.CREATE_TIME
     *
     * @return the value of MOCHA_SECU_RESOURCE.CREATE_TIME
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_RESOURCE.CREATE_TIME
     *
     * @param createTime the value for MOCHA_SECU_RESOURCE.CREATE_TIME
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_RESOURCE.DESCN
     *
     * @return the value of MOCHA_SECU_RESOURCE.DESCN
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getDescn() {
        return descn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_RESOURCE.DESCN
     *
     * @param descn the value for MOCHA_SECU_RESOURCE.DESCN
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setDescn(String descn) {
        this.descn = descn == null ? null : descn.trim();
    }
    
    @Override
   	public String toString() {
   		StringBuilder builder = new StringBuilder();
   		builder.append("Resource [id=")
   				.append(this.id)
   				.append(",name=")
   				.append(this.name)
   				.append(",resType=")
   				.append(this.resType)
   				.append(",resources=")
   				.append(this.resources)
   				.append(",orderNum=")
   				.append(this.orderNum)
   				.append(",createTime=")
   				.append(this.createTime)
   				.append(",descn=")
   				.append(this.descn)
   				.append("]\n");
   		return builder.toString();
   	}
}