package com.mochasoft.fk.security.entity;

public class RolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_ROLE_PERMISSION.ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_ROLE_PERMISSION.ROLE_ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_ROLE_PERMISSION.PER_ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String PerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_ROLE_PERMISSION.ID
     *
     * @return the value of MOCHA_SECU_ROLE_PERMISSION.ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_ROLE_PERMISSION.ID
     *
     * @param id the value for MOCHA_SECU_ROLE_PERMISSION.ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_ROLE_PERMISSION.ROLE_ID
     *
     * @return the value of MOCHA_SECU_ROLE_PERMISSION.ROLE_ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_ROLE_PERMISSION.ROLE_ID
     *
     * @param roleId the value for MOCHA_SECU_ROLE_PERMISSION.ROLE_ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_ROLE_PERMISSION.PER_ID
     *
     * @return the value of MOCHA_SECU_ROLE_PERMISSION.PER_ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getPerId() {
        return PerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_ROLE_PERMISSION.PER_ID
     *
     * @param PerId the value for MOCHA_SECU_ROLE_PERMISSION.PER_ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setPerId(String PerId) {
        this.PerId = PerId == null ? null : PerId.trim();
    }
}