package com.mochasoft.fk.security.entity;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_ROLE.ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_ROLE.NAME
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_ROLE.CREATE_TIME
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOCHA_SECU_ROLE.DESCN
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    private String descn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_ROLE.ID
     *
     * @return the value of MOCHA_SECU_ROLE.ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_ROLE.ID
     *
     * @param id the value for MOCHA_SECU_ROLE.ID
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_ROLE.NAME
     *
     * @return the value of MOCHA_SECU_ROLE.NAME
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_ROLE.NAME
     *
     * @param name the value for MOCHA_SECU_ROLE.NAME
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_ROLE.CREATE_TIME
     *
     * @return the value of MOCHA_SECU_ROLE.CREATE_TIME
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_ROLE.CREATE_TIME
     *
     * @param createTime the value for MOCHA_SECU_ROLE.CREATE_TIME
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOCHA_SECU_ROLE.DESCN
     *
     * @return the value of MOCHA_SECU_ROLE.DESCN
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public String getDescn() {
        return descn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOCHA_SECU_ROLE.DESCN
     *
     * @param descn the value for MOCHA_SECU_ROLE.DESCN
     *
     * @mbggenerated Wed Feb 20 16:25:27 CST 2013
     */
    public void setDescn(String descn) {
        this.descn = descn == null ? null : descn.trim();
    }
	
	@Override
   	public String toString() {
   		StringBuilder builder = new StringBuilder();
   		builder.append("Role [id=")
   				.append(this.id)
   				.append(",name=")
   				.append(this.name)
   				.append(",createTime=")
   				.append(this.createTime)
   				.append(",descn=")
   				.append(this.descn)
   				.append("]\n");
   		return builder.toString();
   	}
}